# Generated by Django 4.1.3 on 2022-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_player_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=1000),
        ),
    ]
