# Generated by Django 4.1.3 on 2022-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_farms_players_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_price', models.IntegerField(default=1)),
                ('seed_price', models.IntegerField(default=25)),
                ('season', models.CharField(default='Spring', max_length=255)),
                ('player_turn', models.IntegerField(default=0)),
            ],
        ),
    ]
