# Generated by Django 4.1.3 on 2022-11-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='farm_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='land_price',
            field=models.IntegerField(default=500),
        ),
    ]
