# Generated by Django 4.1.7 on 2023-04-04 23:37

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('question', models.CharField(max_length=255)),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('A', 'choice_a'), ('B', 'choice_b'), ('C', 'choice_c'), ('D', 'choice_d')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
    ]
