# Generated by Django 4.1.7 on 2023-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyboy', '0002_question_information_url_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
