# Generated by Django 4.1.7 on 2023-04-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soyboy', '0005_comment_delete_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'get_latest_by': 'modified'},
        ),
    ]
